### ISSUE TITLE
Consider offering a more  permissive license for luminare? 

### ISSUE THREAD

**Issue by yujinqiu** [MrKai77/Luminare#10]
Dear Luminare team,
As an indie macOS developer, I'm impressed by Luminare's UI design and would love to use it in my app. However, the GPL license prevents me from doing so, as I prefer to keep my app closed-source.
While I understand Luminare is a core part of Loop and GPL protects your product well, would you consider offering a more permissive license option (like MIT or Apache 2.0) for Luminare library?  
This could broaden its impact and potentially attract more contributors.
I appreciate your work and time considering this request, thanks.

**Comment by MrKai77** [comment]
Hello @yujinqiu!

Thank you for reaching out and for your kind words about our work! As fellow indie macOS developers, we share your commitment to crafting quality software and appreciate the need to balance openness with safeguarding our work. While we recognize the appeal of a more permissive license, we also value ensuring that the work we’ve put into Luminare is credited and safeguarded appropriately. While we have confidence in your intentions, we’ve opted for the GNU GPLv3 license to ensure that the work remains respected and protected in all scenarios.

We hope you understand our position, and we appreciate your understanding and support :D
